import json
import hashlib
from web3 import Web3

# ---- CONFIG ----
RPC_URL = "http://127.0.0.1:8545"
CONTRACT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3"  # your deployed address
PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"  # Account #0 from hardhat node

# Path to the ABI generated by Hardhat
ABI_PATH = "../artifacts/contracts/CTIAnchor.sol/CTIAnchor.json"

# ---- CONNECT TO BLOCKCHAIN ----
w3 = Web3(Web3.HTTPProvider(RPC_URL))
print("Connected:", w3.is_connected())

account = w3.eth.account.from_key(PRIVATE_KEY)

# ---- LOAD CONTRACT ----
with open(ABI_PATH) as f:
    contract_json = json.load(f)
abi = contract_json["abi"]

contract = w3.eth.contract(address=CONTRACT_ADDRESS, abi=abi)

# ---- SAMPLE STIX JSON (this will come from Dev 1 later) ----
stix_data = {
    "type": "relationship",
    "relationship_type": "exploits",
    "source": "Threat Actor X",
    "target": "Vulnerability Z"
}

report_id = "report_001"

# ---- HASH THE DATA ----
stix_string = json.dumps(stix_data, sort_keys=True)
hash_bytes = hashlib.sha256(stix_string.encode()).digest()

print("STIX Data:", stix_string)
print("SHA-256 Hash:", hash_bytes.hex())

# ---- SEND TO BLOCKCHAIN ----
nonce = w3.eth.get_transaction_count(account.address)

txn = contract.functions.anchorHash(report_id, hash_bytes).build_transaction({
    "from": account.address,
    "nonce": nonce,
    "gas": 200000,
    "gasPrice": w3.eth.gas_price
})

signed_txn = w3.eth.account.sign_transaction(txn, private_key=PRIVATE_KEY)
tx_hash = w3.eth.send_raw_transaction(signed_txn.raw_transaction)
print("Transaction sent! Hash:", tx_hash.hex())

receipt = w3.eth.wait_for_transaction_receipt(tx_hash)
print("Transaction confirmed in block:", receipt.blockNumber)

# ---- VERIFY ----
stored_hash, timestamp = contract.functions.verifyHash(report_id).call()
print("Stored Hash on Blockchain:", stored_hash.hex())
print("Timestamp:", timestamp)